// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfjrFHHDLFl6uBVKy6iShBqj-RYNVQJWs',
    appId: '1:160669709059:web:a3ba50b0a760529956af36',
    messagingSenderId: '160669709059',
    projectId: 'project-13c7a',
    authDomain: 'project-13c7a.firebaseapp.com',
    storageBucket: 'project-13c7a.firebasestorage.app',
    measurementId: 'G-HWRR0MRD83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS8KqVTRY1pjDH7AjUCQf0SwOB6XNk_6g',
    appId: '1:160669709059:android:1492045797bb5e2e56af36',
    messagingSenderId: '160669709059',
    projectId: 'project-13c7a',
    storageBucket: 'project-13c7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcqJcb4AAZ4yA1fZ-1odpA3OLdPbmMWjM',
    appId: '1:160669709059:ios:85d872c13ada5e3556af36',
    messagingSenderId: '160669709059',
    projectId: 'project-13c7a',
    storageBucket: 'project-13c7a.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );
}
